image: node:latest

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

stages:
  - test
  - sonarqube-check
  - sonarqube-vulnerability-report

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: test
  script:
    - npm ci

run_tests:
  stage: test
  script:
    - npm ci
    - npm run test:cov
  artifacts:
    paths:
      - coverage/
    expire_in: 1 day

sonarqube-check:
  image: sonarsource/sonar-scanner-cli:latest
  stage: sonarqube-check
  dependencies:
    - run_tests
  script:
    - sonar-scanner -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'

sonarqube-vulnerability-report:
  stage: sonarqube-vulnerability-report
  script:
    - 'curl -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL}/api/issues/gitlab_sast_export?projectKey=${SONAR_PROJECT_KEY}&branch=${CI_COMMIT_BRANCH}&pullRequest=${CI_MERGE_REQUEST_IID}" -o gl-sast-sonar-report.json'
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'
  artifacts:
    expire_in: 1 day
    reports:
      sast: gl-sast-sonar-report.json
